default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: support_backend_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>

test:
  <<: *default
  database: support_backend_test
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>

production:
  primary: &primary_production
    <<: *default
    database: support_backend_production
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV["DB_PORT"] %>

  cache:
    <<: *primary_production
    database: support_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: support_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: support_backend_production_cable
    migrations_paths: db/cable_migrate
